package report

import (
	"strings"

	"github.com/chainguard-dev/darkfiles2/internal/image"
)

// Category classifies a dark file into a bucket so users can distinguish
// expected noise from genuinely suspicious files.
type Category int

const (
	// CategoryUnknown is the bucket that matters: files with no obvious
	// explanation that may warrant investigation.
	CategoryUnknown Category = iota

	// CategoryDeviceFile — entries under /dev (character/block devices, pipes, sockets).
	CategoryDeviceFile

	// CategoryPkgManagerState — package manager databases, caches, lock files, and
	// world/world_lock/triggers that track installed state but aren't "owned" by
	// any individual package.
	CategoryPkgManagerState

	// CategoryRuntimeGenerated — files that the OS or init system generates at
	// boot/runtime: /etc/passwd, /etc/ld.so.cache, /run/*, /tmp/*, etc.
	CategoryRuntimeGenerated

	// CategoryBuildMetadata — image-build artefacts left by tools like apko, ko,
	// Dockerfile COPY instructions that write manifests, and embedded SBOMs.
	CategoryBuildMetadata
)

func (c Category) String() string {
	switch c {
	case CategoryDeviceFile:
		return "Device files"
	case CategoryPkgManagerState:
		return "Package manager state"
	case CategoryRuntimeGenerated:
		return "Runtime-generated"
	case CategoryBuildMetadata:
		return "Build metadata"
	default:
		return "Unknown"
	}
}

// Classify assigns a dark file to a category.
func Classify(f image.File) Category {
	p := f.Path

	// /dev/** — device nodes and special files.
	if strings.HasPrefix(p, "/dev/") {
		return CategoryDeviceFile
	}

	// Package manager state files that aren't owned by any single package.
	if isPkgManagerState(p) {
		return CategoryPkgManagerState
	}

	// Runtime / OS-generated files.
	if isRuntimeGenerated(p) {
		return CategoryRuntimeGenerated
	}

	// Build tooling metadata left in the image.
	if isBuildMetadata(p) {
		return CategoryBuildMetadata
	}

	return CategoryUnknown
}

func isPkgManagerState(p string) bool {
	prefixes := []string{
		// APK (Alpine / Wolfi)
		"/etc/apk/",
		"/lib/apk/db/",
		"/usr/lib/apk/db/",
		"/var/cache/apk/",
		"/var/lib/apk/",
		// dpkg / apt (Debian / Ubuntu)
		"/var/lib/dpkg/",
		"/var/cache/apt/",
		"/var/lib/apt/",
		"/etc/apt/",
		// debconf — the Debian package configuration database
		"/var/cache/debconf/",
		// update-alternatives state
		"/etc/alternatives/",
		// RPM / dnf / yum
		"/var/lib/rpm/",
		"/var/cache/dnf/",
		"/var/cache/yum/",
		"/var/lib/dnf/",
		// In-image SBOM databases
		"/var/lib/db/sbom/",
	}
	for _, pfx := range prefixes {
		if strings.HasPrefix(p, pfx) {
			return true
		}
	}
	return false
}

func isRuntimeGenerated(p string) bool {
	// Exact files commonly generated at runtime.
	exact := map[string]bool{
		"/etc/environment":   true,
		"/etc/fstab":         true,
		"/etc/group":         true,
		"/etc/group-":        true,
		"/etc/gshadow":       true,
		"/etc/gshadow-":      true,
		"/etc/hostname":      true,
		"/etc/hosts":         true,
		"/etc/ld.so.cache":   true,
		"/etc/ld.so.conf":    true,
		"/etc/localtime":     true,
		"/etc/motd":          true,
		"/etc/mtab":          true,
		"/etc/networks":      true,
		"/etc/nsswitch.conf": true,
		"/etc/passwd":        true,
		"/etc/passwd-":       true,
		"/etc/protocols":     true,
		"/etc/resolv.conf":   true,
		"/etc/rpc":           true,
		"/etc/services":      true,
		"/etc/shadow":        true,
		"/etc/shadow-":       true,
		"/etc/shells":        true,
		"/etc/subgid":        true,
		"/etc/subuid":        true,
	}
	if exact[p] {
		return true
	}

	// Directory prefixes that hold only runtime state.
	prefixes := []string{
		"/etc/ld.so.conf.d/",
		"/run/",
		"/tmp/",
		"/var/log/",
		"/var/run/",
		"/var/tmp/",
		"/var/spool/",
		"/proc/",
		"/sys/",
		// PAM runtime config generated by pam-auth-update.
		"/etc/pam.d/",
		"/var/lib/pam/",
		// systemd unit state managed by deb-systemd-helper.
		"/var/lib/systemd/",
		// systemd machine-id etc.
		"/etc/machine-id",
		// shells state managed by update-shells.
		"/var/lib/shells",
	}
	for _, pfx := range prefixes {
		if strings.HasPrefix(p, pfx) {
			return true
		}
	}
	return false
}

func isBuildMetadata(p string) bool {
	exact := map[string]bool{
		"/etc/apko.json":          true,
		"/etc/ko-app":             true, // ko build metadata
		"/var/lib/db/sbom":        true,
	}
	if exact[p] {
		return true
	}
	prefixes := []string{
		"/var/lib/db/sbom/",
		"/.dockerenv",
	}
	for _, pfx := range prefixes {
		if strings.HasPrefix(p, pfx) {
			return true
		}
	}
	// Dockerfile-inserted metadata files at root level.
	if p == "/.dockerenv" {
		return true
	}
	return false
}
