name: Build and push image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write #for cosign

env:
  KO_DOCKER_REPO: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: chainguard-actions/actions-checkout@77ae33bc0f88edf3dada8f2f8217f27a8f93df83 # v7.0.0

      - name: Set up Go
        uses: chainguard-actions/actions-setup-go@a5e8c9530cdd8d86c8c1e22fe4e2d0668896f7c7 # v6.5.0
        with:
          go-version-file: go.mod

      - name: Log in to ghcr.io
        uses: chainguard-actions/docker-login-action@93c9fb113ac946f14a332842652ec9600e25babc # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set-up cosign to sign image
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Set up ko to build image
        uses: chainguard-actions/ko-build-setup-ko@02f91de813b49a4d423ecd4826aaaa9d1aa152f7 # v0.10

      - name: Build and push image
        run: |
           img=$(ko build ./ --bare --tags "${GITHUB_REF_NAME},${GITHUB_SHA}")
           cosign sign ${img} --yes \
               -a sha=${{ github.sha }} \
               -a run_id=${{ github.run_id }} \
